### ISSUE TITLE
你好！

### ISSUE THREAD

**Issue by ColerYu** [zhangshiqian1214/skynet-game#1]
最近在使用zhangshiqian1214/sproto-js，请问zhangshiqian1214/sproto-js/a这个文件怎么生成的啊？
谢谢了！

**Comment by zhangshiqian1214** [comment]
你好, a是使用lua sproto的sprotoparser生成的,类似protobuf的pb文件
local parser = require "sprotoparser"
local sprotoGen = {}

function sprotoGen.create(files, outfile)
	local output = ""
	for _, v in pairs(files) do
		local filename = v
		local f = assert(io.open(filename), "Can't open sproto file")
		local data = f:read "a"
		output = output .. "\n" .. data
	end
	local file = io.open(outfile, "w+b")
	file:write(parser.parse(output))
	file:close()
end

return sprotoGen

**Comment by ColerYu** [comment]
谢谢！
